name: Deploy

on:
  workflow_run:
    workflows: Symfony
    branches: main
    types: completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - run: cp .gitignore.prod .gitignore
      - run: git init
      - name: Cache dependencies Node.js
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ./public/build
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: git add .
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m '${{ github.ref }}'
      - run: git push --force https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git HEAD